### ISSUE TITLE
 Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by workingxx92** [kkoooqq/fakebrowser#18]
Macbooks-MacBook-Pro:reg_account macbookpro$ node index.js 
(node:56955) UnhandledPromiseRejectionWarning: Error: Cannot find module 'lodash'
Require stack:
- /Users/macbookpro/Desktop/Users/source-code/reg_account/node_modules/fakebrowser/dist/cjs/plugins/evasions/user-agent-override/index.js
- /Users/macbookpro/Desktop/Users/source-code/reg_account/node_modules/fakebrowser/dist/cjs/PptrPatcher.js
- /Users/macbookpro/Desktop/Users/source-code/reg_account/node_modules/fakebrowser/dist/cjs/Driver.js
- /Users/macbookpro/Desktop/Users/source-code/reg_account/node_modules/fakebrowser/dist/cjs/FakeBrowser.js
- /Users/macbookpro/Desktop/Users/source-code/reg_account/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/macbookpro/Desktop/Users/source-code/reg_account/node_modules/fakebrowser/dist/cjs/plugins/evasions/user-agent-override/index.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:56955) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:56955) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

{
  "dependencies": {
    "axios": "^0.24.0",
    "express": "^4.17.1",
    "fakebrowser": "^0.0.40",
    "puppeteer": "^10.4.0"
  }
}

**Comment by kkoooqq** [comment]
I'm driving I'll look at it after I get to my destination about an hour.

**Comment by kkoooqq** [comment]
done. 0.0.41
