### ISSUE TITLE
Changing browser lang / ua ?

### ISSUE THREAD

**Issue by krychaj5** [kkoooqq/fakebrowser#23]
Hello, in puppteer-extra I can easily use _user-agent-override_ evasion to set browser ua/lang before launch.
I was trying something as shown in example at https://github.com/kkoooqq/fakebrowser/blob/main/src/plugins/evasions/user-agent-override/index.js
but when I was trying to use it like FakeBrowser.use() / builder.use()

It was giving me errors:

`TypeError: FakeBrowser.use is not a function`
`TypeError: builder.use is not a function`

How is that possible in fakebrowser?

**Comment by kkoooqq** [comment]
user-agent-override/index.js I copied from puppeteer-extra and made some changes, but I forgot exactly what I changed, and I also forgot to remove the example

If you want to modify lang / ua, you can directly modify the contents of the device descriptor file.

Key point: device properties come from the configuration [device-hub](https://github.com/kkoooqq/fakebrowser/tree/main/device-hub), not from the code.

This is the difference between fakebrowser and other frameworks.

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/43202488/140260530-4fd68083-4578-4407-837e-1c118e06e211.png">

**Comment by kkoooqq** [comment]
Have you solved your problem?

**Comment by krychaj5** [comment]
Yes, now I'm manipulating desired properties with windowsDD object.

But sometimes it gives me some errors and won't launch the browser:
`AssertionError [ERR_ASSERTION]: deviceDesc illegal

    at Function.checkLaunchParamsLegal (C:\Users\Lenovo\Desktop\app\node_modules\fakebrowser\dist\cjs\FakeBrowser.js:121:29)
    at Function.<anonymous> (C:\Users\Lenovo\Desktop\app\node_modules\fakebrowser\dist\cjs\FakeBrowser.js:148:18)
    at Generator.next (<anonymous>)
    at C:\Users\Lenovo\Desktop\app\node_modules\fakebrowser\dist\cjs\FakeBrowser.js:28:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Lenovo\Desktop\app\node_modules\fakebrowser\dist\cjs\FakeBrowser.js:24:12)
    at Function.launch (C:\Users\Lenovo\Desktop\app\node_modules\fakebrowser\dist\cjs\FakeBrowser.js:144:16)
    at FakeBrowserBuilder.<anonymous> (C:\Users\Lenovo\Desktop\app\node_modules\fakebrowser\dist\cjs\FakeBrowser.js:96:48)
    at Generator.next (<anonymous>)
    at C:\Users\Lenovo\Desktop\app\node_modules\fakebrowser\dist\cjs\FakeBrowser.js:28:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Lenovo\Desktop\app\node_modules\fakebrowser\dist\cjs\FakeBrowser.js:24:12)
    at FakeBrowserBuilder.launch (C:\Users\Lenovo\Desktop\app\node_modules\fakebrowser\dist\cjs\FakeBrowser.js:95:16)
    at Object.module.exports.runBrowser (C:\Users\Lenovo\Desktop\app\PC\fk.js:48:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='`

appears when I'm setting window outerHeight/Width equals to innerHeight/Width (changing only inner values runs browser properly)

my solution was to multiply outer values by 1.1 

and the other one, I can't handle

`Error: Protocol error (Target.createTarget): Failed to open a new tab
    at C:\Users\Lenovo\Desktop\app\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:63

    at new Promise (<anonymous>)
    at Connection.send (C:\Users\Lenovo\Desktop\app\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:70:16)
    at Browser._createPageInContext (C:\Users\Lenovo\Desktop\app\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:248:53)
    at Browser._createPageInContext (C:\Users\Lenovo\Desktop\app\node_modules\puppeteer-extra\dist\index.cjs.js:211:51)
    at Browser.newPage (C:\Users\Lenovo\Desktop\app\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:241:37)
    at Object.module.exports.runBrowser (C:\Users\Lenovo\Desktop\app\PC\fk.js:42:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\Lenovo\Desktop\app\YouTube\PC\app.js:61:3`
    
    Appears randomly, let my say 1 out of 10 times I'm launching script, then I'm just restarting my node script and it's starting properly (without any code/parameters) changes.

**Comment by kkoooqq** [comment]
Hahahahaha, I didn't write the api documentation, sorry, too busy

**Comment by krychaj5** [comment]
> I didn't write the api documentation, sorry, too busy. Is it finally resolved?

for now - Yes, thanks & gl!
