### ISSUE TITLE
net::ERR_SOCKS_CONNECTION_FAILED

### ISSUE THREAD

**Issue by nhyterke** [kkoooqq/fakebrowser#25]
I've tried to use multiple socks5 proxies but to no avail.

**Error:**
```
Error: net::ERR_SOCKS_CONNECTION_FAILED at https://whatsmyip.com
    at navigate (Z:\Coding\fb\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:155:23)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async FrameManager.navigateFrame (Z:\Coding\fb\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:130:21)
    at async Frame.goto (Z:\Coding\fb\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:500:16)
    at async Page.goto (Z:\Coding\fb\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1167:16)
    at async Z:\Coding\fb\index.js:39:5
```

**Comment by kkoooqq** [comment]
<img width="990" alt="image" src="https://user-images.githubusercontent.com/43202488/141680587-67cb9710-0b70-4517-b9e3-d52f541a7d08.png">


```javascript

const {FakeBrowser} = require('fakebrowser');

!(async () => {
    // https://hideip.me/en/proxy/socks5list
    const builder = new FakeBrowser.Builder()
        .displayUserActionLayer(true)
        .proxy({
            // socks5://ip:port
            // http://ip:port
            // https://ip:port
            proxy: 'socks5://65.21.127.34:1080',
            exportIP: '65.21.127.34',
        })
        .vanillaLaunchOptions({
            headless: false,
        })
        .userDataDir('./fakeBrowserUserData');

    const fakeBrowser = await builder.launch();

    const page = await fakeBrowser.vanillaBrowser.newPage();
    await page.goto('https://whatsmyip.com');
})();


```

works fine on my laptop:

Node 14.16.0
Chrome 95
MacOS 11.5.2

tested in CentOS 7.9 too.
