### ISSUE TITLE
UnhandledPromiseRejectionWarning: ProtocolError: Protocol error (Target.setAutoAttach): Target closed.

### ISSUE THREAD

**Issue by Jiw0cha** [kkoooqq/fakebrowser#27]
Hi

```
const {FakeBrowser} = require('fakebrowser');

!(async () => {
    // Change internal httpserver port number
    FakeBrowser.globalConfig.internalHttpServerPort = 17312

    const builder = new FakeBrowser.Builder()
        .displayUserActionLayer(true)
        .vanillaLaunchOptions({
            headless: false,
            executablePath: '/usr/bin/google-chrome-stable',
        })
        .userDataDir('./fakeBrowserUserData5');

    const fakeBrowser = await builder.launch();
    
    const page = await fakeBrowser.vanillaBrowser.newPage();
    await page.goto('https://whoer.net');
	

    // ***** Do something automatic *****

    // Don't forget to close your browser to release resources
  await fakeBrowser.shutdown();
})();

```

node demo.js

```
(node:2038) UnhandledPromiseRejectionWarning: ProtocolError: Protocol error (Target.setAutoAttach): Target closed.
    at /fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:24
    at new Promise (<anonymous>)
    at CDPSession.send (/fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:222:16)
    at Page._initialize (/fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:177:26)
    at Function.create (/fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:169:20)
    at /fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Target.js:73:88
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async BrowserContext.pages (/fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:461:23)
    at async Promise.all (index 0)
(node:2038) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2038) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2038) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.strict)(browserIndex >= 0)

    at Function._forceShutdown (/fakebrowser/node_modules/fakebrowser/dist/cjs/BrowserLauncher.js:199:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FakeBrowser.shutdown (/fakebrowser/node_modules/fakebrowser/dist/cjs/FakeBrowser.js:174:13)
(node:2038) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

```

node --unhandled-rejections=strict demo.js

```
/fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Target.setAutoAttach): Target closed.
    at /fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:226:24
    at new Promise (<anonymous>)
    at CDPSession.send (/fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:222:16)
    at Page._initialize (/fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:177:26)
    at Function.create (/fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:169:20)
    at /fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Target.js:73:88
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async BrowserContext.pages (/fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:461:23)
    at async Promise.all (index 0) {
  originalMessage: undefined
}

```
Run on linux.

node --version
v12.22.5
{
  "dependencies": {
    "axios": "^0.24.0",
    "fakebrowser": "0.0.55",
    "puppeteer": "^11.0.0"
  }
}

**Comment by kkoooqq** [comment]
What linux version? is it a desktop environment with support for headful mode?

**Comment by Jiw0cha** [comment]
> which linux version? is it a desktop environment with support for headful mode?

```
cat /etc/*-release
PRETTY_NAME="Devuan GNU/Linux 4 (chimaera)"
NAME="Devuan GNU/Linux"
VERSION_ID="4"
VERSION="4 (chimaera)"
VERSION_CODENAME="chimaera"
ID=devuan
ID_LIKE=debian
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"
BUG_REPORT_URL="https://bugs.devuan.org/"
```

**Comment by Jiw0cha** [comment]
> > which linux version? is it a desktop environment with support for headful mode?
> 
> ```
> cat /etc/*-release
> PRETTY_NAME="Devuan GNU/Linux 4 (chimaera)"
> NAME="Devuan GNU/Linux"
> VERSION_ID="4"
> VERSION="4 (chimaera)"
> VERSION_CODENAME="chimaera"
> ID=devuan
> ID_LIKE=debian
> HOME_URL="https://www.devuan.org/"
> SUPPORT_URL="https://devuan.org/os/community"
> BUG_REPORT_URL="https://bugs.devuan.org/"
> ```
> 
> DE xfce, with xorg

I see as browser open window and quickly close/

**Comment by kkoooqq** [comment]
> > which linux version? is it a desktop environment with support for headful mode?
> 
> ```
> cat /etc/*-release
> PRETTY_NAME="Devuan GNU/Linux 4 (chimaera)"
> NAME="Devuan GNU/Linux"
> VERSION_ID="4"
> VERSION="4 (chimaera)"
> VERSION_CODENAME="chimaera"
> ID=devuan
> ID_LIKE=debian
> HOME_URL="https://www.devuan.org/"
> SUPPORT_URL="https://devuan.org/os/community"
> BUG_REPORT_URL="https://bugs.devuan.org/"
> ```
> 
> DE xfce, with xorg I see as browser open window and quickly close.

thanks for the details

**Comment by kkoooqq** [comment]
hi bro, do you have a chat tool that let me to contact you directly? I need to know more details. Thanks!

**Comment by Jiw0cha** [comment]
> hi bro, do you have a chat tool that let me to contact you directly? I need to know more details. Thanks!

https://t.me/ahGh2guurahp

**Comment by kkoooqq** [comment]
Remove singleprocess will work

**Comment by J4c5** [comment]
@kkoooqq  how to "Remove Singleprocess" ?
