### ISSUE TITLE
SOCKS5 proxy with auth

### ISSUE THREAD

**Issue by EureqSClub1707** [kkoooqq/fakebrowser#34]
Socks5 proxy dont work with fake browser: 
```
Error: net::ERR_SOCKS_CONNECTION_FAILED at https://abrahamjuliot.github.io/creepjs/
    at navigate (C:\Users\eureq\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:155:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FrameManager.navigateFrame (C:\Users\eureq\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:
130:21)
    at async Frame.goto (C:\Users\eureq\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:500:16)
    at async Page.goto (C:\Users\eureq\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1167:16)
```
But http proxy with auth works absolutely fine

**Comment by EureqSClub1707** [comment]
If you have same issue, i can recommend https://github.com/MihaZupan/HttpToSocks5Proxy, you will able to convert external SOCKS5 auth proxy to local HTTP proxy without auth.

**Comment by kkoooqq** [comment]
OKAY, ill make a patch to solve this issue, thanks so much!

**Comment by kkoooqq** [comment]
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/43202488/148544668-544918ce-08e4-4bb4-9334-2ad81c8ebd95.png">


It works fine in my side, please check that your socks5 server is working properly.
