### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by Baker68** [kkoooqq/fakebrowser#40]
I am trying to run `demo3-fake-user-action.js` and it outputs : 
```
This instance has been shutdown and turned into a zombie.
(node:39241) UnhandledPromiseRejectionWarning: Error: net::ERR_TOO_MANY_REDIRECTS at https://google.com/
    at navigate (/home/pcb/Desktop/tools/fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:155:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FrameManager.navigateFrame (/home/pcb/Desktop/tools/fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:130:21)
    at async Frame.goto (/home/pcb/Desktop/tools/fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:500:16)
    at async Page.goto (/home/pcb/Desktop/tools/fakebrowser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
    at async /home/pcb/Desktop/tools/fakebrowser/fakebrowser/demo/demo3-fake-user-action.js:16:9
(node:39241) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:39241) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
what am I doing wrong ?
Thanks in advance

**Comment by kkoooqq** [comment]
NodeJS version?
OS Version?

**Comment by Baker68** [comment]
@kkoooqq 
node `v12.22.7` 
npm `v7.24.2`
OS `Linux ROG-Strix-G712LU-G712LU 5.11.0-44-generic #48~20.04.2-Ubuntu SMP Tue Dec 14 15:36:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by 327135569** [comment]
Same problem with proxy enable. but it's ok to open other sites. seems there are some antibot.

**Comment by kkoooqq** [comment]
> Same problem with proxy enable. but it's ok to open other sites. seems there are some antibot.
> 
> npm 6.14.15
> 
> node v14.18.1
> 
> 版本 Windows 10 专业版 版本号 21H2 安装日期 ‎2021/‎11/‎12 操作系统内部版本 19044.1415 体验 Windows Feature Experience Pack 120.2212.3920.0

You could open a new issue to discuss this.
